# .github/actions/sonar-scan/action.yml
name: "Reusable SonarQube Analysis"
description: "Run SonarQube analysis with dynamic project names for pull requests and main branch"

inputs:
  project_key:
    description: "SonarQube project key"
    required: true
  sonar_host_url:
    description: "SonarQube server URL"
    required: true
  sonar_token:
    description: "SonarQube authentication token"
    required: true
  pr_number:
    description: "SonarQube analysis key"
    required: true

runs:
  using: "composite"
  steps:
    - name: echo creds
      run: |
        echo "token= ${{ inputs.sonar_token }}"
        echo "key= ${{ inputs.sonar_host_url }}"
        echo "key= ${{ inputs.pr_number }}"
      shell: bash


    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}  # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ inputs.project_key }}
          -Dsonar.scm.provider=git
          -Dsonar.projectVersion=${{inputs.pr_number}}
          
          
    # - name: Run SonarQube Scanner
    #   run: |
    #     sonar-scanner \
    #       -Dsonar.projectKey=${{ inputs.project_key }} \
    #       -Dsonar.host.url=${{ inputs.sonar_host_url }} \
    #       -Dsonar.login=${{ inputs.sonar_token }}
    #   shell: bash
