# .github/actions/sonar-scan/action.yml
name: "Reusable SonarQube Analysis"
description: "Run SonarQube analysis with dynamic project names for pull requests and main branch"

inputs:
  project_key:
    description: "SonarQube project key"
    required: true
  sonar_host_url:
    description: "SonarQube server URL"
    required: true
  sonar_token:
    description: "SonarQube authentication token"
    required: true

runs:
  using: "composite"
  steps:
    # - name: Set up Java
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: "11"
    #     distribution: 'temurin'
    #     cache: 'true'


    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.1.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}  # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ inputs.project_key }} 
          
    # - name: Run SonarQube Scanner
    #   run: |
    #     sonar-scanner \
    #       -Dsonar.projectKey=${{ inputs.project_key }} \
    #       -Dsonar.host.url=${{ inputs.sonar_host_url }} \
    #       -Dsonar.login=${{ inputs.sonar_token }}
    #   shell: bash
